GUTSHackathon/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

urlpatterns = patterns('',
                       url(r'^$', 'django.contrib.auth.views.login', {'template_name':'users/login.html', 'extra_context':{'next':'/user/home'}}, name='login'),
                       url(r'^user/', include('users.urls', namespace='user')),
)

# Service MEDIA from here if in DEBUG mode.
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}))
    

users/urls.py
from django.conf.urls import patterns, include, url

from users import views

urlpatterns = patterns('',
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'users/login.html', 'extra_context':{'next':'/'}}, name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'/'}, name='logout'),
                       url(r'^associate/$', views.associate, name='associate'),
                       url(r'^associate-response/$', views.associate_callback, name='associate-response'),
                       url(r'^home/$', views.home, name='home'),
                       url(r'^devices/$', views.devices, name='devices'),
                       url(r'^device/$', views.device_by_id, name='devices_by_id'),
                       url(r'^profile/$', views.profile, name='profile'),
                       url(r'^device/rename$', views.change_device_name, name='renamedevice'),
)

users/models.py
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class CustomUserManager(BaseUserManager):
    
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)
    
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)
    
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    
    app_tracker_id = models.CharField(_('app tracker id'), max_length=30, blank=True)
    
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)
    
    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()
    
    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])


class Device(models.Model):
    TYPE_CHOICES = (('NA','What am I?'),
                    ('MOB', 'Mobile'),
                    ('TAB', 'Tablet'),
                    ('PC', 'Computer'))

    owner = models.ForeignKey('User')
    device_id = models.CharField(max_length=500)
    device_name = models.CharField(max_length=50)
    device_type = models.CharField(max_length=3, choices=TYPE_CHOICES)
    user = models.CharField(max_length=50)
    last_checked = models.CharField(max_length=50)


class Application(models.Model):
    device = models.ForeignKey('Device')
    appname = models.CharField(max_length=100)
    total_time = models.IntegerField()

class Session(models.Model):
    dev_app = models.ForeignKey('Application')
    time_spent = models.IntegerField()
    time_stamp = models.IntegerField()

class Notification(models.Model):
    time_stamp = models.IntegerField() 
    device = models.ForeignKey('Device')
    session = models.ForeignKey('Session')
# applications = {'facebook':{'total':23232323232, 'sessions':[ {'startTime':23232322323,'length':223232}, {'startTime':23232322323,'length':223232}],
#                 'snapchat':{'total':23232323232, 'sessions':[ {'startTime':23232322323,'length':223232}, {'startTime':23232322323,'length':223232}],
#                 }

users/forms.py
from django import forms

class RegisterForm(forms.Form):
    first_name = forms.CharField(label="", required=True, max_length=30,
                                    widget=forms.TextInput(attrs={'class':'form-control',
                                                                  'autofocus':'True',
                                                                  'placeholder':'First name'
                                                                  }))
    
    last_name = forms.CharField(label="", required=True, max_length=30,
                                widget=forms.TextInput(attrs={'class':'form-control',
                                                              'placeholder':'Last name'
                                                              }))
    
    mobile_number = forms.CharField(label="", required=True, max_length=30,
                                widget=forms.TextInput(attrs={'class':'form-control',
                                                              'placeholder':'Mobile number'
                                                              }))

    email = forms.EmailField(label="", required=True,
widget=forms.TextInput(attrs={'class':'form-control',
                                                           'placeholder':'Email address'
                                                           }))
    
    password = forms.CharField(label="", required=True, min_length=8,
                               widget=forms.PasswordInput(attrs={'class':'form-control',
                                                                 'placeholder':'Password'
                                                                 }))
    

users/views.py
from users.models import User, Device, Application, Session, Notification
from users.forms import RegisterForm
from django.shortcuts import render, HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
import json, urllib2
from datetime import datetime, timedelta
from api import API_KEY
from notification_sender import sendmail

def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'users/register.html', {'form':form, 'valid':True})
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User(email=data['email'],
                        first_name=data['first_name'],
                        last_name=data['last_name'],
                        is_staff=False, is_active=True, is_superuser=False,
                        last_login=timezone.now(), date_joined=timezone.now())
            user.set_password(data['password'])
            user.save()

            user.backend='django.contrib.auth.backends.ModelBackend' 
            login(request, user)
            return HttpResponseRedirect('/user/associate/')
        else:
            return render(request, 'users/register.html', {'form':form, 'valid':False})

@login_required
def associate(request):
    return render(request, 'users/associate.html', {'api_key':API_KEY})

@login_required
def associate_callback(request):
    if 'user_id' in request.GET:
        print request.GET
        user = request.user
        print user
        user.app_tracker_id = request.GET['user_id']
        user.save()
        retrieve_devices(user)
        return HttpResponseRedirect('/user/home')
    else:
        return HttpResponseRedirect('/user/associate/')

def retrieve_devices(user):
    url = 'https://tethys.dcs.gla.ac.uk/AppTracker/api/v2/devices?key=%s&user_id=%s' % (API_KEY, user.app_tracker_id)
    devices = json.load(urllib2.urlopen(url))
    user_devices = user.device_set.all()
    
    print "Devices:"
    for device in devices:
        print device['device'],
        if not user_devices.filter(device_id=device['device']):
            device = Device(owner=user, device_id=device['device'], 
                            device_name=device['device'], user='Someone', 
                            device_type='NA')
            device.save()
            retrieve_device_usageDB(device, True)
            print "added to user"
        else: 
            print "Device already exists"
   
@login_required            
def home(request):
    devices = request.user.device_set.all()
    notification_list = []
    for device in devices:
        n = get_notifications(device)
        for notification in n:
            added = False
            if len(notification_list) == 0:
                notification_list = [notification]
            for x in range(len(notification_list)):
                if notification.time_stamp > notification_list[x].time_stamp:
                    notification_list = notification_list[:x] + [notification] + notification_list[x:]  
                    added = True
                    break
            if not added:
                notification_list += [notification]
    return render(request, 'users/home.html', {'notifications':notification_list})

@login_required
def devices(request):
    devices = request.user.device_set.all()
    notification_list= []

    for device in devices:
        retrieve_device_usageDB(device, False)
        n = get_notifications(device)
        for notification in n:
            added = False
            if len(notification_list) == 0:
                print "first item"
                notification_list = [notification]
            for x in range(len(notification_list)):
                if notification.time_stamp > notification_list[x]:
                    print "added"
                    notification_list = notification_list[:x] + [notification] + notification_list[x:]  
                    added = True
                    break
            if not added:
                print "blab"
                notification_list += [notification]

    print "notifications: ", notification_list
    return render(request, 'devices/devices.html', {'devices':devices, 
                                                    'notifications':notification_list})

@login_required
def device_by_id(request):
    if 'id' not in request.GET:
        print "no device id"
        return HttpResponseRedirect('/user/devices')
    device = request.user.device_set.filter(device_id=request.GET['id'])
    if len(device) == 0:
        print "Couldn't find device"
        return HttpResponseRedirect('/user/devices')

    applications = device[0].application_set.all()
    appSessions = {}
    for app in applications:
        appSessions[app.appname] = {}
        appSessions[app.appname]['sessions'] = app.session_set.all()
        appSessions[app.appname]['total_time'] = app.total_time

    notification_list = []
    n = get_notifications(device[0])
    for notification in n:
        added = False
        if len(notification_list) == 0:
            print "first item"
            notification_list = [notification]
        for x in range(len(notification_list)):
            if notification.time_stamp > notification_list[x]:
                print "added"
                notification_list = notification_list[:x] + [notification] + notification_list[x:]  
                added = True
                break
        if not added:
            print "blab"
            notification_list += [notification]

    print appSessions
    return render(request, 'devices/device.html', {'device':device[0], 
                                                   'appSessions':appSessions, 
                                                   'notifications':notification_list})

def retrieve_device_usageDB(device, massive):
    #IMEI:353918057929438 2013-11-22+02:00
    t_now = datetime.now()
    end = t_now.strftime("%Y-%m-%d+%H:%M")
    print "Last check:", device.last_checked
    print "Time now:",  end
    deviceApps = device.application_set.all()
    for app in deviceApps:
        print "this device already has", app.session_set.all(), app.appname, "sessions"
    print "===================== notifications"
    get_notifications(device)
    if device.last_checked == end:
      print "No time elapsed since last check"
      return

    device.last_checked = end
    if massive:
        start =  (t_now - timedelta(days=30)).strftime("%Y-%m-%d+%H:%M")
    else:
        start =  (t_now - timedelta(minutes=5)).strftime("%Y-%m-%d+%H:%M")

    print "Checking usage for time:", start, "until", end
    url = 'https://tethys.dcs.gla.ac.uk/AppTracker/api/v2/log?key=%s&device=%s&from=%s&to=%s' % (API_KEY, device.device_id, 
                                                                                                 start, end)
    print url
    sessions = json.load(urllib2.urlopen(url))
    print "There are :", len(sessions), "new sessions"

    for session in sessions:
        print session['app']
        print deviceApps
        app = deviceApps.filter(appname=session["app"])
        print app
        if len(app) == 0:
            app = Application(device=device, appname=session['app'], total_time=session['timespent'])
            app.save()
            sesh = Session(dev_app=app, time_spent=session['timespent'], time_stamp=session['timestamp'])
            print app.appname
        else:
            app = app[0]
            sesh = Session(dev_app=app, time_spent=session['timespent'], time_stamp=session['timestamp'])
            app.total_time += session['timespent']
            app.save()
            
        sesh.save()
        if not massive and ((sesh.time_spent / 1000) > 1):
            print "added a notification"
            notification = Notification(device=device,session=sesh, time_stamp=sesh.time_stamp)
            notification.save()
            sendmail("Appage", "You have a new notification", device.owner.email)
    device.save()
    
@login_required 
def profile(request):
    return render(request, 'users/profile.html', {'user': request.user })

def get_notifications(device):
    return device.notification_set.all()

@login_required
def change_device_name(request):
    if request.method == 'POST':
        device = request.user.device_set.filter(device_id=request.POST['id'])[0]
        device.device_name = request.POST['name']
        device.user = request.POST['username']
        device.save()
    return HttpResponseRedirect(('/user/device?id=%s' % device.device_id))

users/templates/users/.#home.html
gary@think.2764:1383380826

users/templates/users/associate.html
{% extends 'base.html' %}

{% block content %}
<div class="container centered-form">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <form action="https://tethys.dcs.gla.ac.uk/AppTracker/api/v2/request" method="POST" class="form-signin">
        <div class="form-signin-heading">
          <h2 class="sub-heading">AppTracker Login</h2>
        </div>
        <hr />
	
        <input type="hidden" name="key" value="{{ api_key }}"/>
        <input type="hidden" name="callback" value="http://localhost:8000/user/associate-response?" />
        <input name="email" placeholder="Email" class="form-control"/>
        <input type="password" name="password" placeholder="Password" class="form-control" />
        <input type="submit" value="Associate" class="btn btn-lg btn-primary btn-block" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load user_extras %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 form-signin-heading">
      <h1>
        <span class="sub-heading">app</span>age
      </h1>
      <hr />
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div id="buttons">
        <button type="button" class="btn btn-primary btn-circle btn-xl" onclick="location.href='{% url 'user:profile' %}'">Profile</button>
        <button type="button" class="btn btn-info btn-circle btn-xl" onclick="location.href='{% url 'user:devices' %}'">Devices</button>
        <button type="button" class="btn btn-danger btn-circle btn-xl" onclick="location.href='{% url 'user:logout' %}'">Logout</button>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Notifications</h3>
        </div>
        <div class="panel-body">
          {% for notification in notifications %}
          <div class="alert alert-danger notification"><strong>{{ notification|get_dev_name }}</strong><br /> {{ notification|get_app_name }} was used {{ notification.time_stamp|convert_date }} for {{ notification|get_notification_timespent}}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="container centered-form">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <form class="form-signin" method="post">
        <div class="form-signin-heading">
          <h1><span class="sub-heading">app</span>age</h1>
        </div>
	
        {% csrf_token %}
        {% if form.errors %}
        <p>Your username and password didn't match.</p>
        {% endif %}
        
        <input type="text" name="username" class="form-control" placeholder="Email" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <input type="hidden" name="next" value="{{ next }}" />
        
        <label class="checkbox pull-left">
          <input type="checkbox" value="remember-me">
          Remember me
        </label>
        <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
      </form>
      <a href="{% url 'user:register' %}" class="text-center new-account">Create an account </a>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 form-signin-heading">
      <h1 onclick="window.location='/user/home';">
        <span class="sub-heading">app</span>age
      </h1>
      <hr />
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="page-header">
        <h1>{{ user.first_name }} {{ user.last_name }} <small>Profile</small></h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Personal Details</h3>
        </div>
        <div class="panel-body">
	  
          <form accept-charset="UTF-8" role="form" class="col-md-5">
            <legend>Notification e-mail</legend>
            <fieldset>
              <div class="form-group">
                <input class="form-control" placeholder="{{ user.email }}" name="name" type="text">
              </div>
              <input class="btn btn-lg btn-success btn-block" type="submit" value="Update">
            </fieldset>
          </form>
	  
          <form accept-charset="UTF-8" role="form" class="col-md-5 col-md-offset-2">
            <legend>Notification number</legend>
            <fieldset>
              <div class="form-group">
                <input class="form-control" placeholder="07562770346" name="name" type="text">
              </div>
              <input class="btn btn-lg btn-success btn-block" type="submit" value="Update">
            </fieldset>
          </form>
          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container centered-form">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <form class="form-signin" method="post">
        <div class="form-signin-heading">
          <h2 class="sub-heading">Registration</h2>
        </div>
        <hr />
        
        {% csrf_token %}
        {% if form.errors %}
        <p class="error">
          Please correct the error{{ form.errors|pluralize }} below.
        </p>
        {% endif %}
        <div class="control-group">
          {{ form.first_name }}
          <div class="error">
            {{ form.first_name.errors }}
          </div>
        </div>
        <div class="control-group">
          {{ form.last_name }}
          <div class="error">
            {{ form.last_name.errors }}
          </div>
        </div>
        <div class="control-group">
          {{ form.mobile_number }}
          <div class="error">
            {{ form.mobile_number.errors }}
          </div>
        </div>
        <div class="control-group">
          {{ form.email }}
          <div class="error">
            {{ form.email.errors }}
          </div>
        </div>
        <div class="control-group">
          {{ form.password }}
          <div class="error">
            {{ form.password.errors }}
          </div>
        </div>
        <input type="submit" name="submit" value="Register"
               class="btn btn-lg btn-primary btn-block" />
      </form>
    </div>
  </div>
</div>
{% endblock %}